name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on multiple Node versions

    steps:
    - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json # Cache frontend dependencies

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci # Use ci for faster, reliable installs

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test -- --watchAll=false # Run tests non-interactively
      env:
        CI: true # Set CI environment variable for react-scripts test

    # Add steps for backend testing here once available
    # - name: Install Backend Dependencies
    #   working-directory: ./backend
    #   run: npm ci
    # - name: Run Backend Tests
    #   working-directory: ./backend
    #   run: npm test
